In [2]:
import torch

In [3]:
# how to perform random sampling of the tensors

In [4]:
torch.manual_seed(1234)

In [5]:
torch.manual_seed(1234)
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [7]:
#generate random numbers from a statistical distribution

In [8]:
torch.Tensor(4, 4).uniform_(0, 1) #random number from uniform distribution

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [9]:
#now apply the distribution assuming the input values from the 
#tensor are probabilities

In [10]:
torch.bernoulli(torch.Tensor(4, 4).uniform_(0, 1))

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [1., 1., 0., 0.]])

In [11]:
#how to perform sampling from a multinomial distribution

In [12]:
torch.Tensor([10, 10, 13, 10,34,45,65,67,87,89,87,34])

tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.])

In [13]:
torch.multinomial(torch.tensor([10., 10., 13., 10., 
                                34., 45., 65., 67., 
                                87., 89., 87., 34.]), 
                  3)

tensor([ 8,  7, 11])

In [14]:
torch.multinomial(torch.tensor([10., 10., 13., 10., 
                                34., 45., 65., 67., 
                                87., 89., 87., 34.]), 
                  5, replacement=True)

tensor([ 5, 10,  5,  9, 10])

In [15]:
#generate random numbers from the normal distribution

In [16]:
torch.normal(mean=torch.arange(1., 11.), 
             std=torch.arange(1, 0, -0.1))

tensor([1.2111, 2.3034, 3.5310, 4.7278, 6.1060, 6.3294, 6.9060, 7.9908, 9.3492,
        9.9928])

In [17]:
torch.normal(mean=0.5, 
             std=torch.arange(1., 6.))

tensor([-1.1794, -2.9019,  2.4459,  7.5613,  5.9058])

In [18]:
torch.normal(mean=0.5, 
             std=torch.arange(0.2,0.6))

tensor([0.7487])

In [19]:
#computing the descriptive statistics: mean
torch.mean(torch.tensor([10., 10., 13., 10., 34., 
                         45., 65., 67., 87., 89., 87., 34.]))

tensor(45.9167)

In [20]:
# mean across rows and across columns
d = torch.randn(4, 5)
d

tensor([[-0.2632, -0.5432, -1.6406,  0.9295, -1.2777],
        [-0.7428,  0.9711,  0.3551,  0.8562, -0.3635],
        [-0.1552, -1.2282, -0.8039, -0.4530, -0.2217],
        [-2.0901, -1.2658, -1.8761, -0.6066,  0.7470]])

In [21]:
torch.mean(d,dim=0)

tensor([-0.8128, -0.5165, -0.9914,  0.1815, -0.2789])

In [22]:
torch.mean(d,dim=1)

tensor([-0.5590,  0.2152, -0.5724, -1.0183])

In [23]:
#compute median
torch.median(d,dim=0)

(tensor([-0.7428, -1.2282, -1.6406, -0.4530, -0.3635]),
 tensor([1, 2, 0, 2, 1]))

In [24]:
torch.median(d,dim=1)

(tensor([-0.5432,  0.3551, -0.4530, -1.2658]), tensor([1, 2, 3, 1]))

In [25]:
# compute the mode
torch.mode(d)

(tensor([-1.6406, -0.7428, -1.2282, -2.0901]), tensor([2, 0, 1, 0]))

In [26]:
torch.mode(d,dim=0)

(tensor([-2.0901, -1.2658, -1.8761, -0.6066, -1.2777]),
 tensor([3, 3, 3, 3, 0]))

In [27]:
torch.mode(d,dim=1)

(tensor([-1.6406, -0.7428, -1.2282, -2.0901]), tensor([2, 0, 1, 0]))

In [28]:
#compute the standard deviation
torch.std(d)

tensor(0.9237)

In [29]:
torch.std(d,dim=0)

tensor([0.8890, 1.0459, 1.0087, 0.8243, 0.8287])

In [30]:
torch.std(d,dim=1)

tensor([0.9987, 0.7507, 0.4458, 1.1436])

In [31]:
#compute variance
torch.var(d)

tensor(0.8532)

In [32]:
torch.var(d,dim=0)

tensor([0.7903, 1.0939, 1.0175, 0.6795, 0.6868])

In [33]:
torch.var(d,dim=1)

tensor([0.9974, 0.5636, 0.1987, 1.3079])

In [34]:
# compute min and max
torch.min(d)

tensor(-2.0901)

In [35]:
torch.min(d,dim=0)

(tensor([-2.0901, -1.2658, -1.8761, -0.6066, -1.2777]),
 tensor([3, 3, 3, 3, 0]))

In [36]:
torch.min(d,dim=1)

(tensor([-1.6406, -0.7428, -1.2282, -2.0901]), tensor([2, 0, 1, 0]))

In [37]:
torch.max(d)

tensor(0.9711)

In [38]:
torch.max(d,dim=0)

(tensor([-0.1552,  0.9711,  0.3551,  0.9295,  0.7470]),
 tensor([2, 1, 1, 0, 3]))

In [39]:
torch.max(d,dim=1)

(tensor([ 0.9295,  0.9711, -0.1552,  0.7470]), tensor([3, 1, 0, 4]))

In [40]:
# sorting a tensor
torch.sort(d)

(tensor([[-1.6406, -1.2777, -0.5432, -0.2632,  0.9295],
         [-0.7428, -0.3635,  0.3551,  0.8562,  0.9711],
         [-1.2282, -0.8039, -0.4530, -0.2217, -0.1552],
         [-2.0901, -1.8761, -1.2658, -0.6066,  0.7470]]),
 tensor([[2, 4, 1, 0, 3],
         [0, 4, 2, 3, 1],
         [1, 2, 3, 4, 0],
         [0, 2, 1, 3, 4]]))

In [41]:
torch.sort(d,dim=0)

(tensor([[-2.0901, -1.2658, -1.8761, -0.6066, -1.2777],
         [-0.7428, -1.2282, -1.6406, -0.4530, -0.3635],
         [-0.2632, -0.5432, -0.8039,  0.8562, -0.2217],
         [-0.1552,  0.9711,  0.3551,  0.9295,  0.7470]]),
 tensor([[3, 3, 3, 3, 0],
         [1, 2, 0, 2, 1],
         [0, 0, 2, 1, 2],
         [2, 1, 1, 0, 3]]))

In [42]:
torch.sort(d,dim=0,descending=True)

(tensor([[-0.1552,  0.9711,  0.3551,  0.9295,  0.7470],
         [-0.2632, -0.5432, -0.8039,  0.8562, -0.2217],
         [-0.7428, -1.2282, -1.6406, -0.4530, -0.3635],
         [-2.0901, -1.2658, -1.8761, -0.6066, -1.2777]]),
 tensor([[2, 1, 1, 0, 3],
         [0, 0, 2, 1, 2],
         [1, 2, 0, 2, 1],
         [3, 3, 3, 3, 0]]))

In [43]:
torch.sort(d,dim=1,descending=True)

(tensor([[ 0.9295, -0.2632, -0.5432, -1.2777, -1.6406],
         [ 0.9711,  0.8562,  0.3551, -0.3635, -0.7428],
         [-0.1552, -0.2217, -0.4530, -0.8039, -1.2282],
         [ 0.7470, -0.6066, -1.2658, -1.8761, -2.0901]]),
 tensor([[3, 0, 1, 4, 2],
         [1, 3, 2, 4, 0],
         [0, 4, 3, 2, 1],
         [4, 3, 1, 2, 0]]))

In [45]:
from torch.autograd import Variable

In [47]:
Variable(torch.ones(2,2),requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [53]:
a, b = 12,23
x1 = Variable(torch.randn(a,b),
            requires_grad=True)
x2 = Variable(torch.randn(a,b),
            requires_grad=True)
x3 =Variable(torch.randn(a,b),
            requires_grad=True)

In [66]:
c = x1 * x2
d = a + x3
e = torch.sum(d)

e.backward()

print(e)

tensor(3326.2632, grad_fn=<SumBackward0>)


In [67]:
x1.data

tensor([[-1.2091,  0.2051,  0.2288, -0.8229, -0.8648,  2.0531, -1.0560,  1.2542,
          0.9729, -0.0688,  0.1807,  1.5699,  0.2850,  1.1012,  0.3664,  1.4716,
          0.8765,  1.2845, -0.1071,  0.2297,  0.1339, -1.1711,  1.1470],
        [-0.1652, -1.0936,  0.3494, -0.2557, -0.2436,  0.0500,  0.4949, -0.7298,
         -0.9913, -1.0336, -0.5741, -0.4406,  0.2856,  0.1470,  0.7052,  1.2541,
          0.8060,  0.4195, -0.9084,  1.8620,  1.0554, -0.3494,  0.6326],
        [ 1.3003, -1.3980,  0.3112, -0.5524, -0.9377,  0.1630,  0.1073,  0.4173,
         -0.0353, -0.7207,  0.5751,  0.2713,  1.9872,  1.8043, -0.3344,  0.9409,
          0.1268, -0.0614,  1.4043,  0.7124,  0.8636,  0.2804, -0.2781],
        [ 0.0365, -1.3312, -0.1628, -0.1240,  2.1133, -0.3764,  0.9087, -1.2966,
         -1.0998, -0.6562,  1.2251,  1.3851,  0.2078, -0.0117, -0.8635, -0.1551,
         -0.8430,  0.0326, -0.9246, -0.6943, -1.9157,  0.6198,  0.3940],
        [-1.5084, -0.1153,  0.7353, -1.2601, -1.6514,  1.110

In [69]:
x2.data

tensor([[-0.7695,  0.5612, -0.8769, -0.2339, -0.9434,  1.4024, -1.2617, -1.2930,
         -0.7356, -2.5015,  0.0557,  0.3000,  0.1149, -0.5691, -1.0529, -2.0725,
         -0.6946,  0.0269,  0.0063,  0.0193, -0.0594, -1.0575,  0.7839],
        [-2.1574,  1.0613, -0.7151,  1.0884,  0.8948, -2.8039, -0.3344, -1.1181,
         -0.9087,  1.0153, -1.3401,  0.8771,  0.3495,  1.6051,  0.8603,  0.0236,
         -2.4061,  0.6586,  1.4788, -0.6594,  0.5899, -1.5961, -0.1953],
        [-0.3770,  0.5746, -0.3294, -0.7120,  0.4099,  0.9356, -0.2261, -0.6855,
         -1.2324,  0.5782, -0.9081,  1.8166,  0.3664, -0.6500, -0.2839,  0.5119,
         -0.1081,  0.7451,  1.0281,  0.5403,  0.1146, -0.4128, -0.8639],
        [ 0.6057, -0.7682,  2.1478,  0.3082,  2.0604, -0.7334, -0.0956, -1.3209,
         -0.2724, -0.1919,  2.0461,  0.4408,  0.0661, -0.5592, -0.8821, -0.5827,
         -1.6342,  0.2203,  0.6228, -1.1802, -0.2303, -1.1923, -0.7451],
        [-0.2909, -0.7119, -1.4216,  1.0757, -0.6441, -2.316

In [75]:
x3.data

tensor([[ 1.9146,  0.9768,  1.0811,  2.0252,  0.0436,  0.6227,  0.8342,  0.4682,
         -0.3286, -1.0412,  0.2525, -3.0444, -0.0577, -1.5756,  0.8429,  0.4200,
         -0.7470, -0.5565,  3.0590, -0.2083, -0.7636,  0.4813,  1.2078],
        [ 0.2497,  0.3805, -1.1350,  0.0787,  1.3208, -2.4296,  0.4169,  0.1749,
          0.9918, -0.5184,  0.6696, -1.9079, -0.2390,  1.1763,  0.3201,  0.0522,
          0.8203,  0.8242,  0.3822, -0.0764, -1.0941,  0.4387,  0.9921],
        [ 0.6686, -1.2147, -0.0678, -0.7077, -0.8408,  0.8591, -1.6349, -0.6366,
         -0.9685, -0.4280,  0.4780,  0.7809, -0.9091, -0.2959,  0.5441,  0.4954,
         -1.7984,  0.8681, -1.0738,  0.7593,  0.3193, -1.3947,  0.3694],
        [ 1.4813,  0.0046,  0.4982, -0.6972,  0.5296,  0.7683, -0.2602, -0.5705,
         -1.5676, -1.1381, -1.3629, -0.5769, -1.3806,  0.5012,  0.1224, -2.2065,
          0.8173,  0.6701,  0.3091,  0.4854,  0.7659,  1.2846,  0.7897],
        [-0.7370,  1.3229, -0.4509,  1.9527, -0.7203,  0.811

In [76]:
import torch
from torch.autograd import Variable

x_data = [11.0, 22.0, 33.0]
y_data = [21.0, 14.0, 64.0]

w = Variable(torch.Tensor([1.0]),  requires_grad=True)  # Any random value

# Before training
print("predict (before training)",  4, forward(4).data[0])

predict (before training) 4 tensor(4.)


In [77]:
# Using forward pass
def forward(x):
    return x * w

In [78]:
# define the Loss function
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

In [79]:
# Run the Training loop
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("\tgrad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data

        # Manually set the gradients to zero after updating weights
        w.grad.data.zero_()

    print("progress:", epoch, l.data[0])

	grad:  11.0 21.0 tensor(-220.)
	grad:  22.0 14.0 tensor(2481.6001)
	grad:  33.0 64.0 tensor(-51303.6484)
progress: 0 tensor(604238.8125)
	grad:  11.0 21.0 tensor(118461.7578)
	grad:  22.0 14.0 tensor(-671630.6875)
	grad:  33.0 64.0 tensor(13114108.)
progress: 1 tensor(39481139200.)
	grad:  11.0 21.0 tensor(-30279010.)
	grad:  22.0 14.0 tensor(171986000.)
	grad:  33.0 64.0 tensor(-3358889472.)
progress: 2 tensor(2590022582665216.)
	grad:  11.0 21.0 tensor(7755301376.)
	grad:  22.0 14.0 tensor(-44050112512.)
	grad:  33.0 64.0 tensor(860298674176.)
progress: 3 tensor(169906757784039325696.)
	grad:  11.0 21.0 tensor(-1986333900800.)
	grad:  22.0 14.0 tensor(11282376818688.)
	grad:  33.0 64.0 tensor(-220344807849984.)
progress: 4 tensor(11145967797036089329319936.)
	grad:  11.0 21.0 tensor(508751660449792.)
	grad:  22.0 14.0 tensor(-2889709562888192.)
	grad:  33.0 64.0 tensor(56436029183229952.)
progress: 5 tensor(731181229735636676902291243008.)
	grad:  11.0 21.0 tensor(-13030450598720307

In [80]:
# After training
print("predict (after training)",  4, forward(4).data[0])

predict (after training) 4 tensor(-9268691075357861748932608.)


In [85]:
z = Variable(torch.Tensor(4, 4).uniform_(-5, 5))
print(z)

tensor([[-2.6830,  2.0509, -2.6185, -3.6709],
        [-4.9271,  3.6834,  4.0502,  3.4515],
        [ 3.4576,  4.5814,  0.0632, -4.6377],
        [-3.1634,  2.9827, -3.9532, -0.6395]])


In [86]:
print('Requires Gradient : %s ' % (z.requires_grad))
print('Volatile : %s ' % (z.volatile))
print('Gradient : %s ' % (z.grad))
print(z.data)

Requires Gradient : False 
Volatile : False 
Gradient : None 
tensor([[-2.6830,  2.0509, -2.6185, -3.6709],
        [-4.9271,  3.6834,  4.0502,  3.4515],
        [ 3.4576,  4.5814,  0.0632, -4.6377],
        [-3.1634,  2.9827, -3.9532, -0.6395]])


C:\Users\Mafoi\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: volatile was removed (Variable.volatile is always False)
  


In [88]:
x = Variable(torch.Tensor(4, 4).uniform_(-4, 5))
y = Variable(torch.Tensor(4, 4).uniform_(-3, 2))
# matrix multiplication
z = torch.mm(x, y)
print(z.size())

torch.Size([4, 4])
